### ISSUE TITLE
Support for RTP over TCP

### ISSUE THREAD

**Issue by lars18th** [alexte/sat-ip-proxy#7]
Hi,

Will be possible to add support for RTP over TCP in the "rtsp-proxy" ?

This will make possible to enable the use over unreliable connections with low latency (for example, wireless point-to-point links).

Thank you!

**Comment by alexte** [comment]
RTSP over TCP has the disadvantage, that it needs retransmits of lost packets for a continuous stream, which means the client has to maintain larger input buffers for very late packets. But Sat-IP 
should be near realtime for fast channel switching. That's why I think UDP is prefered.

MPEG-TS (Transportstream) should be resilient to lost pakets.

I don't plan to include TCP streaming, but feel free to do a patch and send a push request.

**Comment by lars18th** [comment]
Hi @alexte ,

> RTSP over TCP has the disadvantage, that it needs retransmits of lost packets for 
> a continuous stream

Yes! This is the reason for use it over "low latency" networks.

>  That's why I think UDP is prefered.

The SAT>IP protocol supports:
1) RTP without retransmissions (pure UDP with RTP headers).
2) RTP with retransmissions.
3) RTP over TCP.

All three are supported. However, only the most simple is implemented by manufactureres.

> I don't plan to include TCP streaming

I'm sorry to hear that! RTP over TCP is relatively easy to implement.

In any case, thank you for your good job! ;)
